### ISSUE TITLE
law = "makeham" producing values > 1000

### ISSUE THREAD

**Issue by timriffe** [mpascariu/ungroup#12]
Hi Marius!

Is there something wrong with this set of steps? This example data is coming from `DDSQLtools`, where you once left a note to dig deeper if ever a value >1000 were produced. The example data don't seem pathological, and the extrapolation isn't that far. HT @cimentadaj 

```
mx <- c(0.0296771105565131, 0.00665264110919088, 0.00342875960445963, 
        0.00377901902282611, 0.00707116273138672, 0.0134041945263743, 
        0.0184073459431529, 0.0222593253608793, 0.0257132898736745, 0.0360888832546771, 
        0.0481218078806996, 0.0734298380538821, 0.107445906251669, 0.153227233797312, 
        0.192783421516418, 0.254067819476128, 0.349650365024805, 0.604515542507172, 
        0.705407912909985, 0.828063756883144)
x <- c(0,1,seq(5,90,by=5))


M <- MortalityLaw(
  x = x,
  mx = mx,
  fit.this.x = c(75, 80, 85, 90) ,
  law = "makeham",
  opt.method = "poissonL"
) 
pv <- predict(object = M,
              x = c(90, 95, 100, 105, 110))
range(pv)
summary(M)
```

**Comment by mpascariu** [comment]
Hi Tim,

This is a `{MortalityLaws}` issues not related to `{ungroup}`.

The set of steps is correct!

In the example above you are trying to use 4 data points to fit a `makeham` line and then you interpolate between 90 and 110 (using `predict`). The issues arises in the fitting procedure. If you `plot(M)` you will see what is happening. The fitting method is Poisson MLE, however this is not entirely adequate if an exposure is not provided; and a small number of input data points are used this is prone to go wrong (as in this example). If `mx` is used with  `opt.method = "poissonL"` the function sort of extimates the exposure to `1`.

![Rplot](https://user-images.githubusercontent.com/6264977/105014433-b837bf00-5a40-11eb-9920-ad589ca0f65e.png)

Below i am trying to see if this can be fixed.
1. Add an extra point to stabilize the Poisson MLE calibration - OK
```r
M <- MortalityLaw(
  x = x,
  mx = mx,
  fit.this.x = c(70, 75, 80, 85, 90) ,
  law = "makeham",
  opt.method = "poissonL"
) 

plot(M)
```
![Rplot01](https://user-images.githubusercontent.com/6264977/105014548-dc939b80-5a40-11eb-9fb6-8bb80460959a.png)

2. Use an optimization method based on minimizing the error given by a loss function. Keep 4 data points. -- OK
We have six loss functions in the package.

```r
M <- MortalityLaw(
  x = x,
  mx = mx,
  fit.this.x = c(75, 80, 85, 90) ,
  law = "makeham",
  opt.method = "LF2"
) 

plot(M)
```
![Rplot03](https://user-images.githubusercontent.com/6264977/105015650-0ef1c880-5a42-11eb-8e7a-50ebf6950555.png)

The `availableLF()` gives info about the loss functions.
```r
> availableLF()

Loss functions available in the package:

 LOSS FUNCTION                                  CODE     
 L = -[Dx * log(mu) - mu*Ex]                    poissonL 
 L = -[Dx * log(1 - exp(-mu)) - (Ex - Dx)*mu]   binomialL
 L =  [1 - mu/ov]^2                             LF1      
 L =  log[mu/ov]^2                              LF2      
 L =  [(ov - mu)^2]/ov                          LF3      
 L =  [ov - mu]^2                               LF4      
 L =  [ov - mu] * log[ov/mu]                    LF5      
 L =  abs(ov - mu)                              LF6      

LEGEND:
Dx: Death counts
Ex: Population exposed to risk
mu: Estimated value
ov: Observed value

HINT: Most of the functions work well with 'poissonL', however for complex mortality laws like Heligman-Pollard (HP) one can obtain a better fit using other loss functions (e.g. 'LF2'). You are strongly encouraged to test different option before deciding on the final version. The results might be slightly different.
```

NOW, the `MortalityLaw()` could use a feature to automatically detect proper calibration failure or to better restrict the input. However I am not sure when this will be implemented. Until then `opt.method = "LF2"` rarely fails even with the heaviest models like `HP`.

**Comment by timriffe** [comment]
apologies for my hasting posting this in the wrong repo, how embarrassing! In this case, I'll change the default in `DemoTools` to use `"LF2"`. Thanks a bunch for your insight here!
