### ISSUE TITLE
zero tolerance

### ISSUE THREAD

**Issue by timriffe** [mpascariu/ungroup#13]
It seems one could allow for 0s in the count being split with some simple filters. Here's an example, where the open age group (100+) has 0 count, and it breaks. If we only supply up to age 95, then it works. I can imagine some easy filters handling final age groups, or temporarily imputing a positive number for fitting, then putting the 0 back in afterwards. I do not know what the best way to handle 0s in intermediate ages would be, however. Any thoughts?

```
 Age <- c(0,1,seq(5,100,by=5))
 Value <- c(10000, 44170, 44775, 42142, 38464, 34406, 30386, 26933, 23481, 
            20602, 16489, 14248, 9928, 8490, 4801, 3599, 2048, 941, 326, 
            80, 17, 0)
 n <- length(Age)
# error
 pclm(x = Age, y = Value, nlast = 1)
 
# works
 pclm(x = Age[-n], y = Value[-n], nlast = 5)

# putting a positive value in the 0 makes it not break:
# so maybe a before-after treatment would suffice?
 Value2 <- c(10000, 44170, 44775, 42142, 38464, 34406, 30386, 26933, 23481, 
            20602, 16489, 14248, 9928, 8490, 4801, 3599, 2048, 941, 326, 
            80, 17, 5)
 pclm(x = Age, y = Value2, nlast = 1)
```

**Comment by mpascariu** [comment]
hi @timriffe !

All 3 example work for me. Could you `print`  the error in the first example? Thanks a lot.

```r
> plot(pclm(x = Age, y = Value, nlast = 1))
```
![image](https://user-images.githubusercontent.com/6264977/112051753-9d71eb80-8b52-11eb-8106-48d8fda41bd2.png)


```r
> plot(pclm(x = Age[-n], y = Value[-n], nlast = 5))
```
![image](https://user-images.githubusercontent.com/6264977/112051826-acf13480-8b52-11eb-98b6-a531321e25aa.png)

```r
> plot(pclm(x = Age, y = Value2, nlast = 1))
```
![image](https://user-images.githubusercontent.com/6264977/112051889-bda1aa80-8b52-11eb-824a-a0d56fe45915.png)

**Comment by mpascariu** [comment]
FYI
Actually, during the model calibration we are always adding an artificial bin at the end with a very small value and remove it before storing the results. It was observed to return better estimates in the last bin. Kind of the opposite of what you are suggesting. 

See the internal functions: `create.artificial.bin()` and `delete.artificial.bin()`.

**Comment by timriffe** [comment]
I eat my words, in a new R session the first example runs properly for me too [:shrug:]
