### ISSUE TITLE
The use of offset produces negative output rates when input rates are low

### ISSUE THREAD

**Issue by ChristK** [mpascariu/ungroup#8]
Thank you for all your hard work in this very useful package.

I have noticed that when I try to ungroup mortality rates of uncommon diseases I get negative rates in the outputs. For example

```r
library(ungroup) # CRAN version 1.1.0
m1 <- pclm(seq(0, 80, 5), c(0, 0, 0, 0, 0, 0, 0, 0, 5, 15, 10, 17, 20, 30, 40, 45, 49), 21, rep(1e5, 17))
summary(m1$fitted)
# Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
# -1.812e-01 -5.685e-04 -1.947e-04 -4.592e-03 -8.000e-08  0.000e+00 
```
I was wondering if there is a way to constrain rates to non negative values already. Otherwise it might be a good idea to add this constrain in the fitting algorithm.

**Comment by timriffe** [comment]
Hi @mpascariu adding an example to this issue that produces the same bug. Is there any way I can help investigate/fix this?

```
library(ungroup)

a1   <- 0:100
a_10 <- a1 - a1 %% 10
a10  <- seq(0,100,by=10)
y1   <-c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 1, 2, 2, 4, 4, 2, 5, 5, 2, 3, 9, 
6, 9, 8, 8, 6, 14, 6, 9, 16, 24, 15, 25, 8, 32, 28, 48, 40, 33, 
52, 58, 68, 73, 107, 110, 151, 149, 179, 211, 209, 260, 272, 
307, 323, 357, 339, 352, 385, 377, 380, 382, 330, 343, 305, 321, 
264, 256, 272, 285, 239, 178, 153, 108, 100, 79, 42, 32, 22, 
12, 8, 4)


offset <- c(57478, 58491, 59080, 58617, 57863, 57624, 56136, 56619, 56610, 
61823, 62295, 63284, 60832, 56363, 53187, 50997, 48975, 48776, 
48427, 48848, 47680, 48591, 49035, 49790, 53140, 58717, 66215, 
67250, 71495, 72129, 71613, 74167, 74217, 75456, 76871, 77163, 
77109, 78377, 78806, 83394, 91245, 93689, 94701, 97126, 98175, 
99209, 93293, 84098, 78968, 75600, 72690, 68697, 68558, 68786, 
71148, 74015, 70552, 63128, 60892, 59489, 58046, 61412, 65000, 
66124, 65838, 64772, 64256, 63910, 62476, 60265, 57034, 57619, 
57343, 53066, 40461, 41066, 38222, 32232, 29083, 26987, 21884, 
19429, 16635, 14853, 13531, 11962, 10478, 9381, 7857, 6472, 4770, 
3673, 2715, 1917, 1295, 845, 581, 382, 211, 116, 198)

y10  <- tapply(y1,a_10,sum)

# data seem not-weird:
plot(a1, y1 / offset, log = 'y')

M1 <-
  pclm(x = a10,
       y = y10,
       offset = offset, 
       nlast = 1)
plot(M1$fitted)
# maybe it's the 0?
y10[y10 == 0] <- .5
M2 <-
  pclm(x = a10,
       y = y10,
       offset = offset, 
       nlast = 1)
M2$fitted
```

**Comment by mpascariu** [comment]
I see... 😶
I will do some checks and come back to you in a couple of days. 
Thanks @timriffe .

**Comment by mpascariu** [comment]
Hi @ChristK and @timriffe,
Handling very small values in `{ungroup}` can be a delicate matter.  As of today I do not have a solution for restricting the spline method on the positive numbers when working in vicinity of 0's without revamping the entire algorithm.  However, by artificially adjusting your input for the sake of the calibration and reading the results adequately solves the problem... always I'd say.

In the following comments I will give a solution to your examples.

**Comment by mpascariu** [comment]
@ChristK 

Note the multiplication by 100 and addition of a very small no to get rid of 0's.
```r
> m1 <- pclm(seq(0, 80, 5), c(0, 0, 0, 0, 0, 0, 0, 0, 5, 15, 10, 17, 20, 30, 40, 45, 49) * 100 + 1e-10, 21, rep(1e5, 17))
> summary(m1$fitted/100)
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0000000 0.0000000 0.0001127 0.0003435 0.0003951 0.0045340 
```

**Comment by mpascariu** [comment]
@timriffe 

Note the multiplication by 10 and addition of a very small no to get rid of 0's.

```r
> M1 <-
+   pclm(x = a10,
+        y = y10 * 10 + 0.0000001,
+        offset = offset,
+        nlast = 1)
> 
> plot(a1, y1 / offset, log = 'y')
> lines(M1$fitted/10)
```

![image](https://user-images.githubusercontent.com/6264977/112050628-5c2d0c00-8b51-11eb-8ed2-f785eb403db7.png)

**Comment by mpascariu** [comment]
I will leave this issue open just not to forget about the problem.

**Comment by mpascariu** [comment]
We have added a warning message related to this issue in version `1.4.1`. Soon to be published on CRAN.
